import './globals.css'
import { Inter } from 'next/font/google'

import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: '나만의 사이트 만들기',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
          <div className='main-header'>
            <div>설정</div>
          </div>  
        {children}
      </body>
    </html>
  )
}
